<?php
// source code generated by http://restunited.com
// for any feedback/issue, please send to feedback{at}restunited.com

// load models defined for endpoints
foreach (glob(dirname(__FILE__)."/lib/models/*.php") as $filename)
{
      require_once $filename;
}

// load classes for accessing the endpoints
foreach (glob(dirname(__FILE__)."/lib/*.php") as $filename)
{
      require_once $filename;
}
<<<<<<< HEAD
=======


>>>>>>> 77ccc35f6798d0452523f072a68a8ebacbe3d5a8
?>
