#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""



class User(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'id': 'long',
            
            
            'name': 'str',
            
            
            'first_name': 'str',
            
            
            'state': 'str',
            
            
            'photo': 'list[str]',
            
            
            'categories': 'list[Category]',
            
            
            'locations': 'list[Location]',
            
            
            'primitives': 'ShowcaseDatatypePrimitives',
            
            
            'math': 'ShowcaseDatatypeMath',
            
            
            'date': 'ShowcaseDatatypeDate',
            
            
            'create_timestamp': 'DateTime',
            
            
            'modify_timestamp': 'DateTime'
            
        }

        self.attributeMap = {
            
            'id': 'id',
            
            'name': 'name',
            
            'first_name': 'firstName',
            
            'state': 'state',
            
            'photo': 'photo',
            
            'categories': 'categories',
            
            'locations': 'locations',
            
            'primitives': 'primitives',
            
            'math': 'math',
            
            'date': 'date',
            
            'create_timestamp': 'createTimestamp',
            
            'modify_timestamp': 'modifyTimestamp'
            
        }

        
        #ID of the user
        
        self.id = None # long
        
        #Name of the user
        
        self.name = None # str
        
        #First name of the user
        
        self.first_name = None # str
        
        #
        
        self.state = None # str
        
        #demo for java.lang.Byte[]
        
        self.photo = None # list[str]
        
        #demo for java.util.List
        
        self.categories = None # list[Category]
        
        
        self.locations = None # list[Location]
        
        
        self.primitives = None # ShowcaseDatatypePrimitives
        
        
        self.math = None # ShowcaseDatatypeMath
        
        
        self.date = None # ShowcaseDatatypeDate
        
        #created
        
        self.create_timestamp = None # DateTime
        
        #last modified
        
        self.modify_timestamp = None # DateTime
        


