<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */



/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace SwaggerPetstore\models;

use \ArrayAccess;

class Location implements ArrayAccess {
  static $swaggerTypes = array(
      'street' => 'string',
      'zip' => 'string',
      'city' => 'string',
      'country' => 'string',
      'latitude' => 'double',
      'longitude' => 'double'
  );

  static $attributeMap = array(
      'street' => 'street',
      'zip' => 'zip',
      'city' => 'city',
      'country' => 'country',
      'latitude' => 'latitude',
      'longitude' => 'longitude'
  );

  
  public $street; /* string */
  public $zip; /* string */
  public $city; /* string */
  public $country; /* string */
  public $latitude; /* double */
  public $longitude; /* double */

  public function __construct(array $data = null) {
    $this->street = $data["street"];
    $this->zip = $data["zip"];
    $this->city = $data["city"];
    $this->country = $data["country"];
    $this->latitude = $data["latitude"];
    $this->longitude = $data["longitude"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}


